-- creating the table
CREATE TABLE
    Worker (
        WORKER_ID NUMBER PRIMARY KEY,
        FIRST_NAME VARCHAR2 (50),
        LAST_NAME VARCHAR2 (50),
        SALARY NUMBER,
        JOINING_DATE DATE,
        DEPARTMENT VARCHAR2 (50)
    );

INSERT ALL
    INTO Worker (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (001, 'Monika', 'Arora', 100000, TO_DATE('2014-02-20 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'HR')
    INTO Worker (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (002, 'Niharika', 'Verma', 80000, TO_DATE('2014-06-11 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Admin')
    INTO Worker (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (003, 'Vishal', 'Singhal', 300000, TO_DATE('2014-02-20 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'HR')
    INTO Worker (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (004, 'Amitabh', 'Singh', 500000, TO_DATE('2014-02-20 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Admin')
    INTO Worker (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (005, 'Vivek', 'Bhati', 500000, TO_DATE('2014-06-11 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Admin')
    INTO Worker (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (006, 'Vipul', 'Diwan', 200000, TO_DATE('2014-06-11 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Account')
    INTO Worker (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (007, 'Satish', 'Kumar', 75000, TO_DATE('2014-01-20 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Account')
    INTO Worker (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES (008, 'Geetika', 'Chauhan', 90000, TO_DATE('2014-04-11 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Admin')
SELECT * FROM dual;
-- q1
SELECT
    UPPER(FIRST_NAME) AS WORKER_FIRSTNAME
FROM
    Worker;

-- q2
SELECT
    SUBSTR (FIRST_NAME, 1, 3) AS FIRST_THREE_CHARACTERS
FROM
    Worker;

-- q3
SELECT
    INSTR (FIRST_NAME, 'A') AS POSITION_OF_A
FROM
    Worker
WHERE
    FIRST_NAME = 'Amitabh';

-- q4
SELECT
    FIRST_NAME || ' ' || LAST_NAME AS COMPLETE_NAME
FROM
    Worker;

-- q5
SELECT
    *
FROM
    Worker
ORDER BY
    FIRST_NAME ASC,
    DEPARTMENT DESC;

-- q7
SELECT
    *
FROM
    Worker
WHERE
    FIRST_NAME LIKE '%A';

-- q9
SELECT
    COUNT(*) AS Employee_Count
FROM
    Worker
WHERE
    DEPARTMENT = 'Admin';

-- q10
SELECT
    DEPARTMENT,
    COUNT(*) AS num_of_workers
FROM
    Worker
GROUP BY
    DEPARTMENT
ORDER BY
    num_of_workers DESC;

-- q13
SELECT
    WORKER_REF_ID,
    BONUS_DATE,
    BONUS_AMOUNT
FROM
    Bonus MINUS
SELECT
    WORKER_REF_ID,
    AFFECTED_FROM,
    NULL AS BONUS_AMOUNT
FROM
    Title;

-- q14
SELECT
    *
FROM
    Bonus
WHERE
    ROWNUM <= 3;